# to run this docker-compose file, in the background use this command (in this directory):
# docker-compose up -d
version: '3'

services:
  demo-postgres:
    container_name: demo-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: always

  demo-db-setup:
    container_name: demo-db-setup
    image: kilna/liquibase-postgres
    environment:
      - LIQUIBASE_CONTEXT=dev
      - LIQUIBASE_DATABASE=${DB_NAME}
      - LIQUIBASE_CHANGELOG=/liquibase/db.changelog-master.xml
      - LIQUIBASE_USERNAME=${DB_USER}
      - LIQUIBASE_PASSWORD=${DB_PASSWORD}
      - LIQUIBASE_HOST=demo-postgres
    depends_on:
      - demo-postgres
    volumes:
      # the mount point here `/liquibase`, needs to match the path to the LIQUIBASE_CHANGELOG file above
      - ./src/main/liquibase:/liquibase
    command:
      - bash
      - -c
      - |
        set -e
        echo "waiting for the db to be available"
        until nc -z $$LIQUIBASE_HOST $$LIQUIBASE_PORT; do
        echo "the db is not available - sleeping"
        sleep 1
        done
        echo "the db is up"
        liquibase update

networks:
  default:
    external:
      name: demo-app
