DROP TABLE IF EXISTS ADDRESS;

DROP SEQUENCE IF EXISTS ADDRESS_ID_SEQ;

CREATE SEQUENCE ADDRESS_ID_SEQ
START WITH 1
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
CACHE 1;

CREATE TABLE ADDRESS
(
  ADDRESS_ID   BIGINT                   NOT NULL DEFAULT NEXTVAL('ADDRESS_ID_SEQ') PRIMARY KEY,
  STREET       TEXT                     NOT NULL,
  CITY         TEXT                     NOT NULL,
  STATE        TEXT                     NOT NULL,
  PERSON_ID_FK BIGINT                   NOT NULL,
  DATE_CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  DATE_UPDATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT ADDRESS_PERSON FOREIGN KEY (PERSON_ID_FK) REFERENCES PERSON(PERSON_ID)
);

ALTER SEQUENCE ADDRESS_ID_SEQ OWNED BY ADDRESS.ADDRESS_ID;

ALTER TABLE PERSON DROP COLUMN ADDRESS;

