insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (1,'Tennyson','Alexandria','LA',1);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (2,'Crownhardt','Appleton','WI',1);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (3,'Kennedy','Cincinnati','OH',1);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (4,'Shopko','Columbus','OH',2);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (5,'Monica','Mesa','AZ',2);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (6,'Mosinee','Tacoma','WA',2);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (7,'Dahle','Brooklyn','NY',3);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (8,'North','Raleigh','NC',3);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (9,'Arapahoe','Honolulu','HI',3);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (10,'Daystar','Saint Louis','MO',4);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (11,'Daystar','Ogden','UT',4);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (12,'Forest','Kalamazoo','MI',4);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (13,'Arapahoe','Hattiesburg','MS',5);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (14,'Old Gate','Houston','TX',5);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (15,'Mcbride','Amarillo','TX',5);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (16,'Union','Minneapolis','MN',6);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (17,'Lien','Des Moines','IA',6);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (18,'Carberry','Columbus','OH',6);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (19,'Montana','Newark','DE',7);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (20,'Sutherland','Charleston','WV',7);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (21,'Spohn','Des Moines','IA',7);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (22,'Service','Des Moines','IA',8);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (23,'Beilfuss','Scranton','PA',8);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (24,'Vahlen','New York City','NY',8);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (25,'Charing Cross','Lakewood','WA',9);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (26,'Thierer','Kansas City','MO',9);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (27,'Killdeer','El Paso','TX',9);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (28,'Almo','Lakewood','WA',10);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (29,'Hollow Ridge','San Francisco','CA',10);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (30,'Carberry','Delray Beach','FL',10);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (31,'Blackbird','Springfield','IL',11);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (32,'Judy','Jacksonville','FL',11);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (33,'Division','New York City','NY',11);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (34,'Thackeray','Pittsburgh','PA',12);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (35,'Forest Dale','San Luis Obispo','CA',12);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (36,'Briar Crest','Tacoma','WA',12);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (37,'Havey','Washington','DC',13);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (38,'Prentice','Washington','DC',13);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (39,'Tony','Atlanta','GA',13);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (40,'Shopko','Katy','TX',14);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (41,'Coolidge','Waco','TX',14);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (42,'Judy','Washington','DC',14);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (43,'Michigan','Oxnard','CA',15);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (44,'Farmco','Norman','OK',15);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (45,'Warner','Peoria','IL',15);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (46,'Carpenter','Irving','TX',16);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (47,'Anzinger','Boston','MA',16);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (48,'Darwin','Houston','TX',16);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (49,'Harper','Danbury','CT',17);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (50,'Russell','North Little Rock','AR',17);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (51,'Cody','Montgomery','AL',17);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (52,'Stone Corner','Brooklyn','NY',18);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (53,'Anzinger','Detroit','MI',18);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (54,'Summer Ridge','Bridgeport','CT',18);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (55,'Stang','Knoxville','TN',19);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (56,'Meadow Ridge','Boise','ID',19);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (57,'Hoffman','Amarillo','TX',19);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (58,'3rd','Van Nuys','CA',20);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (59,'Nancy','Omaha','NE',20);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (60,'Quincy','Richmond','VA',20);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (61,'Namekagon','Maple Plain','MN',21);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (62,'Golf View','Phoenix','AZ',21);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (63,'Butterfield','Glendale','AZ',21);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (64,'Sage','Washington','DC',22);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (65,'Dennis','El Paso','TX',22);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (66,'West','Saint Paul','MN',22);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (67,'Fallview','Brooklyn','NY',23);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (68,'Ridgeway','Sacramento','CA',23);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (69,'Morrow','Dayton','OH',23);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (70,'Fremont','Mobile','AL',24);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (71,'Ramsey','Philadelphia','PA',24);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (72,'Pankratz','Arlington','VA',24);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (73,'Center','Syracuse','NY',25);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (74,'Atwood','Denver','CO',25);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (75,'Riverside','Seattle','WA',25);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (76,'Crescent Oaks','Philadelphia','PA',26);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (77,'Lunder','Tampa','FL',26);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (78,'Fordem','Clearwater','FL',26);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (79,'Huxley','Detroit','MI',27);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (80,'Westend','Charlottesville','VA',27);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (81,'Fulton','Richmond','VA',27);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (82,'Dawn','Chico','CA',28);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (83,'Mariners Cove','Newark','NJ',28);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (84,'Morningstar','Saint Louis','MO',28);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (85,'Mcbride','Atlanta','GA',29);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (86,'Atwood','Houston','TX',29);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (87,'Forest Dale','Jackson','MS',29);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (88,'Grim','Pittsburgh','PA',30);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (89,'Veith','Cincinnati','OH',30);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (90,'Loeprich','Atlanta','GA',30);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (91,'Browning','Duluth','GA',31);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (92,'Straubel','Nashville','TN',31);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (93,'Lake View','Baton Rouge','LA',31);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (94,'Kedzie','Greenville','SC',32);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (95,'Harbort','Chicago','IL',32);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (96,'Arkansas','Charleston','SC',32);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (97,'Ruskin','Henderson','NV',33);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (98,'Merry','Elizabeth','NJ',33);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (99,'Pond','Dulles','VA',33);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (100,'Fieldstone','Melbourne','FL',34);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (101,'Warrior','Boston','MA',34);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (102,'Vernon','Hampton','VA',34);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (103,'Ridgeview','Pittsburgh','PA',35);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (104,'Eliot','Bloomington','IN',35);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (105,'Merry','Pittsburgh','PA',35);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (106,'La Follette','Lynchburg','VA',36);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (107,'Beilfuss','New York City','NY',36);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (108,'Moose','Carson City','NV',36);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (109,'Lukken','Columbus','OH',37);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (110,'Golf View','Columbus','OH',37);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (111,'Lerdahl','Tallahassee','FL',37);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (112,'Boyd','Lincoln','NE',38);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (113,'Jenna','San Jose','CA',38);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (114,'Dakota','Peoria','IL',38);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (115,'Claremont','Lincoln','NE',39);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (116,'Harbort','Brooklyn','NY',39);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (117,'Veith','Saint Paul','MN',39);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (118,'Anniversary','Mobile','AL',40);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (119,'Charing Cross','Syracuse','NY',40);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (120,'Dwight','Newark','NJ',40);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (121,'Moland','Pinellas Park','FL',41);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (122,'High Crossing','Fort Lauderdale','FL',41);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (123,'Transport','Louisville','KY',41);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (124,'Hazelcrest','Tacoma','WA',42);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (125,'Declaration','Fort Worth','TX',42);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (126,'Alpine','San Diego','CA',42);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (127,'Anthes','Tacoma','WA',43);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (128,'Eagan','Philadelphia','PA',43);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (129,'Mariners Cove','North Port','FL',43);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (130,'Fairview','Fayetteville','NC',44);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (131,'Prairieview','Fresno','CA',44);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (132,'Randy','Baltimore','MD',44);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (133,'Carey','Dallas','TX',45);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (134,'Florence','Naples','FL',45);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (135,'Homewood','Lubbock','TX',45);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (136,'Elka','Salt Lake City','UT',46);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (137,'Loftsgordon','Buffalo','NY',46);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (138,'Northview','Decatur','GA',46);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (139,'Delladonna','Richmond','VA',47);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (140,'Londonderry','Las Vegas','NV',47);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (141,'Moulton','Independence','MO',47);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (142,'Northland','Dayton','OH',48);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (143,'Sullivan','Denver','CO',48);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (144,'Grim','Lake Worth','FL',48);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (145,'Bluestem','Dallas','TX',49);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (146,'Pierstorff','Memphis','TN',49);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (147,'Canary','Rochester','NY',49);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (148,'Ronald Regan','Miami','FL',50);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (149,'Independence','Jamaica','NY',50);
insert into ADDRESS (ADDRESS_ID, STREET, CITY, STATE, PERSON_ID_FK) values (150,'Hudson','Louisville','KY',50);
