DROP TABLE IF EXISTS PERSON;

DROP SEQUENCE IF EXISTS PERSON_ID_SEQ;

CREATE SEQUENCE PERSON_ID_SEQ
START WITH 1
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
CACHE 1;

CREATE TABLE PERSON
(
  PERSON_ID    BIGINT                   NOT NULL DEFAULT NEXTVAL('PERSON_ID_SEQ') PRIMARY KEY,
  NAME         TEXT                     NOT NULL,
  ADDRESS      TEXT                     NOT NULL,
  DATE_CREATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  DATE_UPDATED TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);


ALTER SEQUENCE PERSON_ID_SEQ OWNED BY PERSON.PERSON_ID;
