-- https://www.mockaroo.com/
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (1, 'Odelinda Bowick', '5 Mallory Avenue');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (2, 'Isis Cabrales', '675 Dovetail Junction');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (3, 'Bianca Clearie', '38 Springview Drive');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (4, 'Jany Jellicorse', '279 Reindahl Crossing');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (5, 'Mia Zelake', '73215 Hintze Alley');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (6, 'Piotr Theaker', '6 Dayton Way');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (7, 'Correna Folkes', '09 Waywood Plaza');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (8, 'Martita Philp', '79536 Vermont Pass');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (9, 'Martica Serridge', '710 Bluestem Point');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (10, 'Arnie Warstall', '3 Declaration Way');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (11, 'Ozzy Whitehead', '017 Novick Alley');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (12, 'Mela Chaucer', '1817 Carioca Alley');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (13, 'Charin Walsh', '81390 Blue Bill Park Terrace');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (14, 'Levey Rhelton', '39 Coolidge Parkway');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (15, 'Isiahi Ludewig', '2 Blackbird Circle');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (16, 'Garrett McCrann', '012 Fallview Drive');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (17, 'Any Ellacott', '11 Commercial Court');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (18, 'Verney Swigg', '153 Holmberg Trail');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (19, 'Max Dyte', '4873 Parkside Court');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (20, 'Marchelle Cohani', '4 Knutson Hill');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (21, 'Stace Siggee', '61583 Knutson Center');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (22, 'Wat Davenhill', '037 Acker Alley');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (23, 'Adamo Towle', '03754 Fair Oaks Center');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (24, 'Nikolaus Abramzon', '63 Ohio Drive');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (25, 'Rice Sargent', '00 Washington Center');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (26, 'Avie Densell', '3 Kipling Place');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (27, 'Schuyler Delle', '626 Surrey Plaza');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (28, 'Alfreda Morfey', '72 Surrey Point');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (29, 'Aurelea Burgon', '4 Buhler Junction');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (30, 'Jeni Carlick', '33 Ohio Avenue');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (31, 'Hannah Frean', '357 Pawling Street');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (32, 'Jordan Lowerson', '1499 Nova Park');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (33, 'Deidre Price', '6377 Crownhardt Park');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (34, 'Reina Gomes', '3 Prairieview Place');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (35, 'Graeme Cawkill', '7724 Scott Court');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (36, 'Roze McGiven', '26021 Debs Place');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (37, 'Thedrick Lynett', '4 Ruskin Alley');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (38, 'Barry Gidman', '64 Bobwhite Junction');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (39, 'Cathlene Loosemore', '783 Schiller Alley');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (40, 'Barrie Laurentino', '8377 Michigan Terrace');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (41, 'Dina Speachley', '47179 Tony Junction');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (42, 'Nonah Fellini', '23 Tennessee Drive');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (43, 'Ardisj Storr', '7545 Monica Junction');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (44, 'Daren Mulbery', '7894 Canary Lane');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (45, 'Simeon Wringe', '562 Maple Circle');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (46, 'Caresse Gossart', '29692 Shelley Plaza');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (47, 'Kamilah De Malchar', '747 Bunting Crossing');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (48, 'Henrie Methingam', '9 Walton Parkway');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (49, 'Emmeline Humberstone', '39629 La Follette Terrace');
insert into PERSON (PERSON_ID, NAME, ADDRESS) values (50, 'Sybyl Yeliashev', '45999 Toban Lane');
